spring:
  profiles:
    include: SECRET-KEY
  datasource:
    url: jdbc:mysql://${database-host}:3306/${database-name} //변경 // jdbc:mysql://{RDS 엔드포인트}/{RDS 인스턴스 DB명}
    driver-class-name: com.mysql.cj.jdbc.Driver # jdbc
    username: ${database-username} # RDS에서 생성한 유저네임
    password: ${database-password} # RDS에서 생성한 비밀번호
  h2:
    console:
      enabled: true # H2 콘솔을 활성화합니다.
      path: /h2-console # H2 콘솔의 접근 경로
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # Hibernate의 DDL 자동 생성 전략 (update, create, create-drop 등)
    properties:
      hibernate:
        format_sql: true # 얘는 실제 디비로 나가는 sql을 보여줍니다
        dialect: org.hibernate.dialect.MySQLDialect
  logging.level:
    org.hibernate.SQL: debug